### ISSUE TITLE
Bug: failed to operate with openim-admin-front

### ISSUE THREAD

**Issue by Sylariam** [openimsdk/helm-charts#24] opened 2023-11-22 03:15 UTC
### What happened?

[Background]: I have successfully installed im-server and im-chat, and verified using the official Android app. It works perfectly. Based on my k8s cluster configuration, I did made some modifications, like using Aliyun LB instead of Nginx Ingress.

[Issue]: While exploring openim-admin-front, I encounter a CORS error:
![image](https://github.com/openimsdk/helm-charts/assets/30169866/474e1784-9aba-4d95-a353-3d3d564bd72b)
It seems that the requests from the admin-front are not correctly requesting my cluster service(the request url looks like your official website. is this a default value?). I attempted to search through the source code but found nothing. Could you help me identify this problem?

### What did you expect to happen?

login and use the admin functionalities

### How can we reproduce it (as minimally and precisely as possible)?

access {host}/openim-admin-front/login

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
aliyun
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by cubxxw** [comment] 2023-11-22 06:14
I apologize for any inconvenience caused by the issue regarding the URL prefix in the openim management backend. It seems that we have overlooked the routing for nginx. Rest assured, our team is actively working on resolving this matter. Please allow us some time to rectify the situation. Thank you for bringing this to our attention and for your patience.

**Comment by cubxxw** [comment] 2023-11-28 10:02
The mirror has been updated. Could you please try clearing the local registry.cn-hangzhou.aliyuncs.com/openimsdk/openim-admin-front:latest and then try again? Thank you for your cooperation.

**Comment by cubxxw** [comment] 2023-11-28 12:18
Have you had a chance to update the code and delete any local images? It's an important step in ensuring the latest version is being used. Thank you for your attention to this matter.

**Comment by Sylariam** [comment] 2023-11-29 03:10
> Have you had a chance to update the code and delete any local images? It's an important step in ensuring the latest version is being used. Thank you for your attention to this matter.

I did, currently using:
image:
  # registry.cn-hangzhou.aliyuncs.com/openimsdk/openim-admin-front
  repository: ghcr.io/openimsdk/openim-admin-front
  pullPolicy: Always
  tag: "latest"
  
Access through {my_host}/openim-admin-front/login. 
FYI, I did use Aliyun LB instead of Nginx Ingress. But I doubt this is relevant

**Comment by skiffer-git** [comment] 2024-11-18 08:01
Undergoing comprehensive testing, awaiting updates

**Closed by skiffer-git** 2024-11-18 08:01 UTC
